/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Foundation_RetrieveCPro */

#ifndef _Included_Foundation_RetrieveCPro
#define _Included_Foundation_RetrieveCPro
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Foundation_RetrieveCPro
 * Method:    ImageShow
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Foundation_RetrieveCPro_ImageShow
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
